### ISSUE TITLE
Buttons in Live TV wrong arranged

### ISSUE THREAD

**Issue by SkyBird1980** [gade01/repository.gade#1]
There are some Buttons bugged in Live TV View.
Please Check :)

![screenshot003](https://user-images.githubusercontent.com/4501443/40933777-d6db6cca-6832-11e8-978f-daa52e09a181.png)
(Resized to 1080p)

My Resolution is 3840 x 2160 but that should be no problem.
Tested on Kodi Krypton + Laia Nightly

**Comment by gade01** [comment]
Thanks for reporting the issue.

Should be fixed with https://github.com/gade01/Rapier/commit/9f54027392331e1a64c08848820b3418cc4dec7b

Can you confirm this?

**Comment by gade01** [comment]
You have to copy these recent files from Github to your skin.rapier folder:

includes.xml
VideoOSD.xml

**Comment by SkyBird1980** [comment]
the arrangement ist fixed, but the recording button isn't clickable,
![screenshot004](https://user-images.githubusercontent.com/4501443/40981288-e37520b8-68da-11e8-8fff-5398ba6f4838.png)

**Comment by gade01** [comment]
I haven't touched the record button at all.

The button is enabled if it's possible to record the playing channel. 

You can try the previous version of Rapier's VideoOSD.xml or latest Estuary to see if it's the same. 
And please try with the same channel and content.

**Comment by SkyBird1980** [comment]
I tested it now (still on Krypton):
Estuary:
![screenshot006](https://user-images.githubusercontent.com/4501443/40989688-e37c8a1a-68ee-11e8-9c82-cb63addb7da7.png)

Without Edit:
![screenshot008](https://user-images.githubusercontent.com/4501443/40989705-f4dc5466-68ee-11e8-9ed5-c4367c4dc686.png)

With Edit:
![screenshot007](https://user-images.githubusercontent.com/4501443/40989735-0ee36368-68ef-11e8-9cfa-1a28834dd4c1.png)

**Comment by SkyBird1980** [comment]
I see the problem, your fix was for laia... sorry! :D In Laia there could be more space between CMS & Record
![screenshot011](https://user-images.githubusercontent.com/4501443/40990505-556a83c8-68f1-11e8-8a3b-abda06a2c6b7.png)

**Comment by gade01** [comment]
Absolutely.

I'll look into it and push a development version out later tonight.

**Comment by gade01** [comment]
I just pushed a development version to my repo which should fix all spacing issues.

Thanks!
