### ISSUE TITLE
Bookmark Visible while Live TV

### ISSUE THREAD

**Issue by SkyBird1980** [gade01/repository.gade#2]
Problem: Bookmark is still visible while Live TV. So the Gui is still missaranged. (But not on every Channel so i didn't see it last time)
Solution: Make the Button only visible if no live TV is running.
![screenshot000](https://user-images.githubusercontent.com/4501443/41504376-349c9c1c-71ed-11e8-8d68-a4753da967fa.png)

Used Rapier Version:
11.2.8 / Dev Version on Laia

**Comment by gade01** [comment]
Thanks a lot for reporting.
Fixed now.

Next time please post Rapier related issues for the Rapier skin. This is my development repo only.
